"""
Agent module.
Orchestrates the AI Farmer Advisory workflow by analysing user queries,
dispatching to the appropriate tools, and using Google Gemini to generate
a final advisory message.
"""

import re
from tools.weather import get_weather
from tools.crop import crop_recommendation
from tools.pest import detect_pest
from tools.fertilizer import fertilizer_advice
from gemini_client import ask_gemini

# ---------------------------------------------------------------------------
# Keyword-based intent detection helpers
# ---------------------------------------------------------------------------

def _extract_city(query: str) -> str | None:
    """Try to extract a city name from common patterns like 'weather in <city>'."""
    pattern = r"weather\s+(?:in|for|at|of)\s+([a-zA-Z\s]+)"
    match = re.search(pattern, query, re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return None


def _extract_soil_season(query: str) -> tuple[str | None, str | None]:
    """Extract soil type and season from the query."""
    soils = ["loamy", "black", "clay", "sandy"]
    seasons = ["winter", "summer", "monsoon", "spring", "autumn", "kharif", "rabi"]

    query_lower = query.lower()
    found_soil = next((s for s in soils if s in query_lower), None)
    found_season = next((s for s in seasons if s in query_lower), None)
    return found_soil, found_season


def _extract_crop(query: str) -> str | None:
    """Extract a crop name from the query."""
    crops = [
        "wheat", "rice", "cotton", "millet", "maize",
        "soybean", "groundnut", "sugarcane", "potato", "tomato",
    ]
    query_lower = query.lower()
    return next((c for c in crops if c in query_lower), None)


def _has_pest_symptoms(query: str) -> bool:
    """Check if the query mentions pest/disease symptoms."""
    symptom_keywords = [
        "yellow spots", "holes", "caterpillar", "white powder",
        "powdery", "mildew", "rust", "wilt", "wilting", "blight",
        "pest", "disease", "insects", "bugs", "infection",
        "spots", "eaten", "chewed", "drooping",
    ]
    query_lower = query.lower()
    return any(kw in query_lower for kw in symptom_keywords)


# ---------------------------------------------------------------------------
# Main agent function
# ---------------------------------------------------------------------------

def farmer_agent(query: str) -> str:
    """
    Process a farmer's question by routing it to relevant tools and then
    using Google Gemini to generate a comprehensive advisory.

    Args:
        query: The farmer's natural-language question.

    Returns:
        A detailed advisory string generated by the Gemini model.
    """
    tool_outputs: list[str] = []

    # 1. Weather detection
    city = _extract_city(query)
    if city:
        weather_result = get_weather(city)
        tool_outputs.append(f"[Weather Data]\n{weather_result}")

    # 2. Crop recommendation
    soil, season = _extract_soil_season(query)
    if soil:
        season = season or "monsoon"  # default season if not specified
        crop_result = crop_recommendation(soil, season)
        tool_outputs.append(f"[Crop Recommendation]\n{crop_result}")

    # 3. Pest detection
    if _has_pest_symptoms(query):
        pest_result = detect_pest(query)
        tool_outputs.append(f"[Pest Detection]\n{pest_result}")

    # 4. Fertilizer advice
    crop = _extract_crop(query)
    if crop:
        fert_result = fertilizer_advice(crop)
        tool_outputs.append(f"[Fertilizer Advice]\n{fert_result}")

    # 5. Build the prompt for Gemini
    tool_context = "\n\n".join(tool_outputs) if tool_outputs else "No specific tool data was retrieved."

    prompt = (
        "You are a professional agricultural advisor helping Indian farmers. "
        "Use the data below gathered from specialized tools, along with the farmer's "
        "original question, to compose a clear, helpful, and actionable advisory.\n\n"
        f"### Farmer's Question\n{query}\n\n"
        f"### Tool Data\n{tool_context}\n\n"
        "### Instructions\n"
        "- Summarize the relevant tool findings.\n"
        "- Provide clear, practical advice that a farmer can act on immediately.\n"
        "- If weather data is present, factor it into your advice.\n"
        "- Mention organic/sustainable alternatives where appropriate.\n"
        "- Use simple language; avoid jargon.\n"
        "- Structure your reply with headings and bullet points for readability.\n"
    )

    # 6. Call Gemini for the final advisory
    return ask_gemini(prompt)
